### ISSUE TITLE
Don‘t understand executableSchema's resolvers

### ISSUE THREAD

**Issue by linonetwo** [apollostack/GitHunt-API#4]
At [schema.js](https://github.com/apollostack/GitHunt-API/blob/f0529de6d874d1bd7d7078151f2af82ba8019a68/api/github/schema.js#L29)
there is
```javascript
export const resolvers = {
  Repository: {
    owner: property('owner'),
  },
};
```
where _.property will generating a function likes (obj) => obj['owner']

but what is the object that will pass to this resolver?

**Comment by linonetwo** [comment]
Looking at another Schema.js
```javascript
export const resolvers = {
  Entry: {
    repository({ repository_name }, _, context) {
      return context.Repositories.getByFullName(repository_name);
    },
...
```
the first argument pass to resolver is an object, I believe it's from variables comes together with query.

But why we will pass a query with an object variable, that already containing an 'owner' to the server?

**Comment by jangerhofer** [comment]
This question is better suited to the [Meteor forums](https://forums.meteor.com/c/apollo), but since it's here already, I'll try to help you resolve it.

The first argument passed to a resolver is commonly named `root` or `_` for short.  

> from variables comes together with query.

...is roughly accurate.  In simple terms, that argument contains the previous step in the query chain before the current resolver was called.  This is a better question for the

**Comment by stubailo** [comment]
Yes, the first argument is the return value from the parent resolver. We're working on better server docs that explain resolvers more completely.
